### ISSUE TITLE
no method matching AbstractFloat(::Type{Union{Missing, Float64}})

### ISSUE THREAD

**Issue by xgdgsc** [JeffreySarnoff/RollingFunctions.jl#11]
After upgrading to julia 1.0.3 from 1.0.2. I get error with code that used to work before:

```julia
A = [missing;1;2;3;4;5;0.000000001; -100;0; missing; NaN]
using RollingFunctions
running(sum, A, 2)
```
```julia
ERROR: MethodError: no method matching AbstractFloat(::Type{Union{Missing, Float64}})
Closest candidates are:
  AbstractFloat(::Bool) at float.jl:250
  AbstractFloat(::Int8) at float.jl:251
  AbstractFloat(::Int16) at float.jl:252
  ...
Stacktrace:
 [1] float(::Type) at ./float.jl:269
 [2] running(::Function, ::Array{Union{Missing, Float64},1}, ::Int64) at /home/gsc/.julia/packages/RollingFunctions/DLRrJ/src/running.jl:8
 [3] top-level scope at none:0
```
Adding `RollingFunctions.float(::Type{Union{T,Missing}}) where {T} = Base.float(T)` from https://github.com/JuliaLang/julia/issues/29693 seems a partial workaround for me.

**Comment by JeffreySarnoff** [comment]
I had a bunch of edits (not current master, an earlier one) that covered missings comprehensively and works with Julia v1.1-dev but does not precompile with Julia v1.0.3.  Im considering waiting for v1.1 and using those.   What do you think.

**Comment by xgdgsc** [comment]
That' s fine for me. Currently using my local simple implementation.

**Comment by JeffreySarnoff** [comment]
actually -- it seems sorted out now.  Please try current master and let me know if it works for you.

**Comment by JeffreySarnoff** [comment]
works
