### ISSUE TITLE
Different API with `rolling` function

### ISSUE THREAD

**Issue by scls19fr** [JeffreySarnoff/RollingFunctions.jl#14]
Hello,

I wonder if 

    mean(rolling(data, windowsize))

or with piping operator

    rolling(data, windowsize) |> mean

couldn't be an interesting API 

What is your opinion?

Kind regards

**Comment by JeffreySarnoff** [comment]
What would be involved?

**Comment by scls19fr** [comment]
it could reduce the number of exported functions and provide an API quite similar to Python Pandas and have a kind of object oriented API (by using multiple dispatch)

See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html

An other feature that could be provide could be to also have **expanding** functions.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.expanding.html#pandas.DataFrame.expanding

For example we have `cumsum` and `cumprod` in [Base](https://github.com/JuliaLang/julia/) but not neither `cummax` nor `cummin` https://github.com/JuliaLang/julia/issues/1649

```julia
julia> a
8-element Array{Int64,1}:
 10
 12
 14
  9
 10
  8
 16
 20

julia> cumsum(a)
8-element Array{Int64,1}:
 10
 22
 36
 45
 55
 63
 79
 99
```

a similar approach could be done with expanding functions

See https://github.com/JuliaLang/julia/issues/1649#issuecomment-504539648

**Comment by JeffreySarnoff** [comment]
your `mean(rolling(data, windowsize))` is my `rolling(mean, data, windowsize)`
`rollmean(data, windowsize)` is just a convenience for  `rolling(mean, data, windowsize)`

It wouldn't really reduce the number of exported functions .. I could simply not export the `rollmean` etc and force the user to use `rolling(mean, data, windowsize)` .. also, more importantly, I would have to  overload `mean` and all the others which may cause interoperability issues with other packages down the line (or today).

FYI the general approach was (no disrespect to Pandas) inspired by functions I had used with R.

Adding `cummax` `cummin` etc seems like a good idea.

**Comment by scls19fr** [comment]
`cummin` and `cummax` have been deprecated in favor of `accumulate`

https://github.com/JuliaLang/julia/blob/480703b9d770f82202b8a6daf0b3414fc7e9fad9/HISTORY.md

https://github.com/JuliaLang/julia/pull/18931

**Comment by JeffreySarnoff** [comment]
ok -- thank you for the note
