### ISSUE TITLE
Compatibility with CUDA ?

### ISSUE THREAD

**Issue by HenriDeh** [JeffreySarnoff/RollingFunctions.jl#17]
Currently rolling functions return an array on the cpu no matter the type of the input array. This means that the result must be moved back to the gpu after using it, which is a slow operation.

I guess this must be possible since the base `diff` function (equivalent to `rolling(-,a,2)`) supports CuArrays. But this may require good knowledge of CUDA.jl.

```
julia> using CUDA, RollingFunctions

julia> rolling(sum, cu(rand(10)), 2)
9-element Array{Float32,1}:
 1.5295954
 0.7749236
 1.0564828
 1.523129
 1.328017
 1.4198613
 1.3945057
 0.8062186
 0.24077797
```

**Comment by JeffreySarnoff** [comment]
Fair point.  I don't have that knowledge of CUDA.jl yet.

**Comment by JeffreySarnoff** [comment]
PR is welcome
