### ISSUE TITLE
Option to pad initial values to preserve length?

### ISSUE THREAD

**Issue by pdeffebach** [JeffreySarnoff/RollingFunctions.jl#19]
Came up on discourse. Someone has a DataFrame, 

```
df = DataFrame(y = [1, 2, 3, 4, 5, 6])
```

and they want to add a new column `z` where `z = rolling(sum, df.y, 2)`. 

Unfortunately, this gives a `5` element vector, so you can't use `transform` from DataFrames. 

Can we add a keyword argument to add padding? Could hurt performance because it would change the type of output... but could be a good option to have.

**Comment by JeffreySarnoff** [comment]
Would you have the imputed first [final] value be copied from the determined second [penultimate] value, or linearly extend, or ... ?

**Comment by JeffreySarnoff** [comment]
glad it is available
