### ISSUE TITLE
Overlap with `ImageFiltering.mapwindow`

### ISSUE THREAD

**Issue by timholy** [JeffreySarnoff/RollingFunctions.jl#4]
There seems to be some overlap with ImageFiltering's `mapwindow`:
```julia
help?> ImageFiltering.mapwindow
  mapwindow(f, img, window, [border="replicate"]) -> imgf

  Apply f to sliding windows of img, with window size or indices specified by window. For example, mapwindow(median!, img, window) returns an Array of values similar to img
  (median-filtered, of course), whereas mapwindow(extrema, img, window) returns an Array of (min,max) tuples over a window of size window centered on each point of img.

  The function f receives a buffer buf for the window of data surrounding the current point. If window is specified as a Dims-tuple (tuple-of-integers), then all the integers must be odd
  and the window is centered around the current image point. For example, if window=(3,3), then f will receive an Array buf corresponding to offsets (-1:1, -1:1) from the imgf[i,j] for
  which this is currently being computed. Alternatively, window can be a tuple of AbstractUnitRanges, in which case the specified ranges are used for buf; this allows you to use
  asymmetric windows if needed.

  border specifies how the edges of img should be handled; see imfilter for details.

  For functions that can only take AbstractVector inputs, you might have to first specialize default_shape:

  f = v->quantile(v, 0.75)
  ImageFiltering.MapWindow.default_shape(::typeof(f)) = vec

  and then mapwindow(f, img, (m,n)) should filter at the 75th quantile.

  See also: imfilter.
```
One advantage of `mapwindow` is that it works on arbitrary-dimensional arrays.

I will put a link to RollingFunctions on ImageFiltering's README.

**Comment by JeffreySarnoff** [comment]
Working with arbitrary-dimensional arrays (n-d cuboid windowing) is something I agree is of import.  That you are ahead of me on something array-ful is well-expected!  I will take a look at your work -- and if you notice something that would punch throughput again more in my  [source](https://github.com/JeffreySarnoff/RollingFunctions.jl/blob/master/src/rolling.jl), post an enhancement issue.  I am not looking to fork away from your work -- (rather, had been oblivous :smile: ).

**Comment by timholy** [comment]
Oh, trust me, I'm sure I've duplicated work dozens of times; there's not enough time to keep track of all the cool stuff other people are doing.

Glad that you're also interested in things that I care about! And ImageFiltering brings in a lot of other packages, so there may be some advantage in having a lighter-weight alternative. Nice work on this package.

**Comment by JeffreySarnoff** [comment]
Thank you. I have included a cross-ref in the Readme.
