### ISSUE TITLE
Published documentation is in a bad state

### ISSUE THREAD

**Issue by laborg** [JeffreySarnoff/RollingFunctions.jl#47]
- The content of the published docs for 0.7 is basically "abcd" (https://docs.juliahub.com/RollingFunctions/ThWAA/0.7.0/intro/stepping/)
 - The docs for `dev` are older and are not compatible with 0.7 (https://jeffreysarnoff.github.io/RollingFunctions.jl/dev/)
 - There appears to be some nice updates for the documentation, but they are not published (branch `1`). 

Thanks for this package, but working with it would be way easier if there is a matching documentation.

**Comment by JeffreySarnoff** [comment]
I removed the docs link pending cleanup -- the README has what is needed for now
